### ISSUE TITLE
Dark red is really bright?

### ISSUE THREAD

**Issue by adrawerofthings** [mrmrs/tachyons-colors#4]
Is it meant to be more like the maroon from http://clrs.cc/ ? (currently is only a small bit darker than normal red)

**Comment by mrmrs** [comment]
I'll look into it. I think I didn't want it too dark. 'darkest red' is probably more chill

**Comment by fab1an** [comment]
Is there a darkest-red somewhere? 

@mrms Could you weight in on this, please: https://github.com/tachyons-css/react-native-style-tachyons/issues/11

**Comment by mrkhdly** [comment]
Tachyons v5 will become a monorepo so this issue is being closed, if the issue is still relevant please open an issue with the main repo https://github.com/tachyons-css/tachyons/issues/new & link to this one
