### ISSUE TITLE
No documentation on adding custom stuff

### ISSUE THREAD

**Issue by alan-ws** [mrmrs/tachyons-colors#7]
Hi, I am extremely frustrated. I like using Tachyons but I can't customise anything. I want to add a new colour to my react app and I amend the colour.css file in tachyons and nothing happens. The output tachyons.css file remains the same. How do I add custom stuff to Tachyons?

I added tachyons to my project via npm install. I have tachyons-cli installed globally. What do I need to do to change things and add custom stuff?

**Comment by lachlanjc** [comment]
Hey! Check this out: https://components.ai/tachyons-theme

& this repo: https://github.com/tachyons-css/tachyons-custom
